[LidTitlePanel]
Meter=Shape
Shape=Rectangle 0,0,201,18 | Fill Color 0,0,0,1 | StrokeWidth 1 |Stroke Color 0,255,0,255

[LidACPanelBorder]
Meter=Shape
Y=0R
Shape=Rectangle 0,0,100,60 | Fill Color 0,0,0,1 | StrokeWidth 1 |Stroke Color 0,255,0,255

[LidDCPanelBorder]
Meter=Shape
X=0R
Y=r
Shape=Rectangle 0,0,100,60 | Fill Color 0,0,0,1 | StrokeWidth 1 |Stroke Color 0,255,0,255

[TimeoutTitlePanel]
Meter=Shape
Y=R
Shape=Rectangle 0,0,201,18 | Fill Color 0,0,0,1 | StrokeWidth 1 |Stroke Color 0,255,0,255

[TimeoutACPanelBorder]
Meter=Shape
Y=0R
Shape=Rectangle 0,0,100,48 | Fill Color 0,0,0,1 | StrokeWidth 1 |Stroke Color 0,255,0,255

[TimeoutDCPanelBorder]
Meter=Shape
X=0R
Y=r
Shape=Rectangle 0,0,100,48 | Fill Color 0,0,0,1 | StrokeWidth 1 |Stroke Color 0,255,0,255